# Generated by Django 2.2.4 on 2020-11-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAuthorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='Notes Here'),
            preserve_default=False,
        ),
    ]
