# Generated by Django 2.2.4 on 2020-11-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoAndNinjaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='old dojo'),
            preserve_default=False,
        ),
    ]
